FROM golang:bookworm

RUN apt-get update \
    && apt-get install -y \
        build-essential \
        curl \
        wget 

WORKDIR /minio
RUN curl https://dl.min.io/client/mc/release/linux-amd64/mc \
        --create-dirs \
        -o /minio/mc
RUN chmod +x /minio/mc

# Copy in the binaries
WORKDIR /app
COPY . .
WORKDIR /app/cmd/indexer
RUN make container_build
RUN chmod 755 /app/cmd/indexer/run.sh

CMD ["/app/cmd/indexer/run.sh"]


